python3 CPLEX_CP_C2.py
python3 CPLEX_MIP_C2.py
python3 GUROBI_MIP_C2.py
python3 OR-TOOLS_CP_C2.py
python3 OR-TOOLS_MIP_C2.py
python3 CPLEX_CP_R_SB.py
python3 CPLEX_MIP_R_SB.py
python3 GUROBI_MIP_R_SB.py
python3 OR-TOOLS_CP_R_SB.py
python3 OR-TOOLS_MIP_R_SB.py